### ISSUE TITLE
File preview not working : Consultation Update

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1663]
![fkefwkfew](https://user-images.githubusercontent.com/57055998/127750011-15287626-d4f9-4253-ac04-83677459e5c4.PNG)

in the consultation update, we are unable preview the upload image (png & jpg)

**Comment by shaileshaanand** [comment]
I can't reproduce this bug in staging

**Comment by shaileshaanand** [comment]
@tomahawk-pilot This seems like a content policy issue, please look into it

**Comment by shaileshaanand** [comment]
@bodhish

**Comment by dauntlessnomad** [comment]
@shaileshaanand can you share the error message from console. so i can modify the csp

**Comment by shaileshaanand** [comment]
> @shaileshaanand can you share the error message from console. so i can modify the csp

@nihal467

**Comment by arpancodes** [comment]
@tomahawk-pilot this is the console error... let me know if you need anything more
![image](https://user-images.githubusercontent.com/42417893/128930881-0ff47a19-4d81-45df-a327-da3717c98a9a.png)

**Comment by samholics** [comment]
any updates about the issue ? facilities keep calling about this. nd they totally depend upon this feature.

* preview not working
* downloaded file is not readable but only in codes 
@shaileshaanand @bodhish

**Comment by dauntlessnomad** [comment]
fixed. added the csp entry . please retest

**Comment by arpancodes** [comment]
Still not working in staging @tomahawk-pilot
![image](https://user-images.githubusercontent.com/42417893/129409184-f807bc40-537f-49ab-9f65-7c2c8361adaf.png)

**Comment by aparnacoronasafe** [comment]
@gigincg @tomahawk-pilot @bodhish 

A bug filed in Aug 2021! The issue persists.

**Comment by patelaryan7751** [comment]
issue resolved
