### ISSUE TITLE
Username : must be unique

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#793]
![image](https://user-images.githubusercontent.com/67050716/95557395-625f7e00-0a32-11eb-84e8-66ebf2ae55cc.jpeg)

These two usernames are found to be the same. This will cause confusion and duplication. 

Please name username unique. 

Also, is there a way to delete/edit the one on the left?

**Comment by vigneshhari** [comment]
Solved in the backend ( such users won't be allowed to be created again ), @bodhish handle existing cases with the super admin

**Comment by aparnacoronasafe** [comment]
<img width="1018" alt="Screenshot 2020-10-11 at 4 13 17 PM" src="https://user-images.githubusercontent.com/67050716/95676585-c160f680-0bdc-11eb-92b9-aea4c97921af.png">

Issue remains. just created the ID on the left

**Comment by vigneshhari** [comment]
username is case sensitive isnt it ?
